// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgvuaamfnzdgijzkoxod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndnVhYW1mbnpkZ2lqemtveG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODEwNTEsImV4cCI6MjA3MzQ1NzA1MX0.HYl4tlt_bWLFwYBaFT7Dbx9OhabJYyxg9k5VrM4ObkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});